### ISSUE TITLE
Storing binary files

### ISSUE THREAD

**Issue by Meiendorf** [becoming/02-java-file-service#1]
Since BinTray allows free trial only for one month, can I use GitHub Releases instead for storing my binaries? I found and configured a maven plugin which allows to package and deploy project as GitHub release with binary file as asset automatically, just like deploying to BinTray : https://github.com/jutzig/github-release-plugin
![Untitled1](https://user-images.githubusercontent.com/31164055/56905781-8da61580-6aa9-11e9-8dba-f11c44cee298.png)
![Untitled](https://user-images.githubusercontent.com/31164055/56905780-8da61580-6aa9-11e9-8cdb-992ee6a2bda5.png)

**Comment by rodislav** [comment]
There are simply too much ways for publishing artifacts. I took the Bintray as it is **free for public repositories** and propose a Maven compatible storage. This principle is adopted by most of the Java professionals today, even though they use Nexus _(similar to Bintray)_, but I have not found a free hosted nexus and easy to use from setup perspective.

At the end of the learning process it is important that you learn how companies are doing so that you know it and can find a job that fits you :-) 

I'll add this note to the wiki.

**Comment by rodislav** [comment]
https://github.com/becoming/becoming.github.io/commit/3cd12b16eb8ca640e012575a632de80483981adc
